name: spark
version: ${pluginVersion}
description: ${pluginDescription}
author: Luck
website: https://spark.lucko.me/
main: me.lucko.spark.nukkit.PNXSparkPlugin
api: "2.0.0"
commands:
  spark:
    description: Main plugin command